com.uiux.confluence-macro.aura-button.label=WonikIPS - Button
com.uiux.confluence-macro.aura-button.desc=Embed a customizable button that links to other content.

com.uiux.confluence-macro.aura-cards.label=WonikIPS - Cards
com.uiux.confluence-macro.aura-cards.desc=Embed cards that link to other content to create overviews, instructions, presentations etc.

com.uiux.confluence-macro.aura-panel.label=WonikIPS - Panel
com.uiux.confluence-macro.aura-panel.desc=Embed a customizable panel that organizes & highlights content like Tip, Note, Warning & Info.

com.uiux.confluence-macro.aura-background-fill.label=WonikIPS - Background Color
com.uiux.confluence-macro.aura-background-fill.desc=Embed a background color that can have any content.

com.uiux.confluence-macro.aura-background-image.label=WonikIPS - Background Content
com.uiux.confluence-macro.aura-background-image.desc=Embed a container with a background color and/or image.

com.uiux.confluence-macro.aura-pretty-title.label=WonikIPS - Title
com.uiux.confluence-macro.aura-pretty-title.desc=Embed a highly customizable headline.

com.uiux.confluence-macro.aura-divider.label=WonikIPS - Divider
com.uiux.confluence-macro.aura-divider.desc=Embed a customizable horizontal rule with an optional icon or text.

com.uiux.confluence-macro.aura-tab-collection.label=WonikIPS - Tab Group
com.uiux.confluence-macro.aura-tab-collection.desc=Embed customizable tabs. Insert the Tab Group first. Then add multiple WonikIPS Tabs inside the Tab Group.

com.uiux.confluence-macro.aura-tab.label=WonikIPS - Tab
com.uiux.confluence-macro.aura-tab.desc=Insert this macro into the WonikIPS Tab Group macro for each tab that is needed.
